################################################################################
# Environment script generated by ilcsoft-install on Tue Apr 16 13:27:17 2013
# for Eutelescope located at [ /home/spanns/ilcsoft/v01-17/Eutelescope/HEAD ]
################################################################################


#--------------------------------------------------------------------------------
#     Global Environment Variables
#--------------------------------------------------------------------------------
export MAKEOPTS="-j4"
export CXX="g++"
export ILCSOFT_CMAKE="/home/spanns/ilcsoft/v01-17/ILCSoft.cmake"
export CC="gcc"
export FC="gfortran"
export ILCSOFT_CMAKE_ENV="/home/spanns/ilcsoft/v01-17/ILCSoft.cmake.env.sh"


#--------------------------------------------------------------------------------
#     Eutelescope
#--------------------------------------------------------------------------------
export EUDAQ="/home/spanns/ilcsoft/v01-17/Eutelescope/HEAD/eudaq/trunk"
export MILLEPEDEII="/home/spanns/ilcsoft/v01-17/Eutelescope/HEAD/millepede2/trunk"
export MILLEPEDEII_VERSION="trunk"
export EUDAQ_VERSION="trunk"
export EUTELESCOPE="/home/spanns/ilcsoft/v01-17/Eutelescope/HEAD"
export PATH="$MILLEPEDEII:$EUTELESCOPE/bin:$PATH"
export LD_LIBRARY_PATH="$EUTELESCOPE/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     GEAR
#--------------------------------------------------------------------------------
export GEAR="/home/spanns/ilcsoft/v01-17/gear/v01-03"
export PATH="$GEAR/tools:$GEAR/bin:$PATH"
export LD_LIBRARY_PATH="$GEAR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     ROOT
#--------------------------------------------------------------------------------
export ROOTSYS="/home/spanns/ilcsoft/v01-17/root/5.34.07"
export PATH="$ROOTSYS/bin:$PATH"
export LD_LIBRARY_PATH="$ROOTSYS/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     CLHEP
#--------------------------------------------------------------------------------
export CLHEP="/home/spanns/ilcsoft/v01-17/CLHEP/2.1.3.1"
export CLHEP_BASE_DIR="$CLHEP"
export CLHEP_INCLUDE_DIR="$CLHEP/include"
export PATH="$CLHEP_BASE_DIR/bin:$PATH"
export LD_LIBRARY_PATH="$CLHEP_BASE_DIR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     RAIDA
#--------------------------------------------------------------------------------
export RAIDA_HOME="/home/spanns/ilcsoft/v01-17/RAIDA/v01-06-02"
export PATH="$RAIDA_HOME/bin:$PATH"


#--------------------------------------------------------------------------------
#     Marlin
#--------------------------------------------------------------------------------
export MARLIN="/home/spanns/ilcsoft/v01-17/Marlin/v01-04-01"
export PATH="$MARLIN/bin:$PATH"
export MARLIN_DLL="/home/spanns/ilcsoft/v01-17/CEDViewer/v01-06-01/lib/libCEDViewer.so:/home/spanns/ilcsoft/v01-17/Eutelescope/HEAD/lib/libEutelescope.so:$MARLIN_DLL"


#--------------------------------------------------------------------------------
#     LCCD
#--------------------------------------------------------------------------------
export LCCD="/home/spanns/ilcsoft/v01-17/lccd/v01-02-01"


#--------------------------------------------------------------------------------
#     LCIO
#--------------------------------------------------------------------------------
export LCIO="/home/spanns/ilcsoft/v01-17/lcio/v02-03-03"
export PATH="$LCIO/tools:$LCIO/bin:$PATH"
export LD_LIBRARY_PATH="$LCIO/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     GSL
#--------------------------------------------------------------------------------
export GSL_HOME="/home/spanns/ilcsoft/v01-17/gsl/usr"
export PATH="$GSL_HOME/bin:$PATH"
export LD_LIBRARY_PATH="$GSL_HOME/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     CED
#--------------------------------------------------------------------------------
export PATH="/home/spanns/ilcsoft/v01-17/CED/v01-08/bin:$PATH"


#--------------------------------------------------------------------------------
#     GBL
#--------------------------------------------------------------------------------
export GBL="/home/spanns/ilcsoft/v01-17/GBL/v01-15-00"
export LD_LIBRARY_PATH="$GBL/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     CMake
#--------------------------------------------------------------------------------
export PATH="/home/spanns/ilcsoft/v01-17/CMake/usr/bin:$PATH"


#--------------------------------------------------------------------------------
#     ILCUTIL
#--------------------------------------------------------------------------------
export ilcutil="/home/spanns/ilcsoft/v01-17/ilcutil/v01-00"
export LD_LIBRARY_PATH="$ilcutil/lib:$LD_LIBRARY_PATH"
# --- additional comands ------- 
