################################################################################
# Environment script generated by ilcsoft-install on Thu Mar 21 11:59:17 2013
# for Eutelescope located at [ /home/spanns/ilcsoft/v01-16-02/Eutelescope/HEAD ]
################################################################################


#--------------------------------------------------------------------------------
#     Global Environment Variables
#--------------------------------------------------------------------------------
export MAKEOPTS="-j4"
export CXX="g++"
export ILCSOFT_CMAKE="/home/spanns/ilcsoft/v01-16-02/ILCSoft.cmake"
export CC="gcc"
export FC="gfortran"
export ILCSOFT_CMAKE_ENV="/home/spanns/ilcsoft/v01-16-02/ILCSoft.cmake.env.sh"


#--------------------------------------------------------------------------------
#     Eutelescope
#--------------------------------------------------------------------------------
export EUDAQ="/home/spanns/ilcsoft/v01-16-02/Eutelescope/HEAD/eudaq/trunk"
export MILLEPEDEII="/home/spanns/ilcsoft/v01-16-02/Eutelescope/HEAD/millepede2/trunk"
export MILLEPEDEII_VERSION="trunk"
export EUDAQ_VERSION="trunk"
export EUTELESCOPE="/home/spanns/ilcsoft/v01-16-02/Eutelescope/HEAD"
export PATH="$MILLEPEDEII:$MILLEPEDEII:$EUTELESCOPE/bin:$PATH"
export LD_LIBRARY_PATH="$EUTELESCOPE/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     GEAR
#--------------------------------------------------------------------------------
export GEAR="/home/spanns/ilcsoft/v01-16-02/gear/v01-02-02"
export PATH="$GEAR/tools:$GEAR/bin:$PATH"
export LD_LIBRARY_PATH="$GEAR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     ROOT
#--------------------------------------------------------------------------------
export ROOTSYS="/home/spanns/ilcsoft/v01-16-02/root/5.34.04"
export PATH="$ROOTSYS/bin:$PATH"
export LD_LIBRARY_PATH="$ROOTSYS/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     CLHEP
#--------------------------------------------------------------------------------
export CLHEP="/home/spanns/ilcsoft/v01-16-02/CLHEP/2.1.1.0"
export CLHEP_BASE_DIR="$CLHEP"
export CLHEP_INCLUDE_DIR="$CLHEP/include"
export PATH="$CLHEP_BASE_DIR/bin:$PATH"
export LD_LIBRARY_PATH="$CLHEP_BASE_DIR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     RAIDA
#--------------------------------------------------------------------------------
export RAIDA_HOME="/home/spanns/ilcsoft/v01-16-02/RAIDA/v01-06-02"
export PATH="$RAIDA_HOME/bin:$PATH"


#--------------------------------------------------------------------------------
#     Marlin
#--------------------------------------------------------------------------------
export MARLIN="/home/spanns/ilcsoft/v01-16-02/Marlin/v01-04"
export PATH="$MARLIN/bin:$PATH"
export MARLIN_DLL="/home/spanns/ilcsoft/v01-16-02/Eutelescope/HEAD/lib/libEutelescope.so:$MARLIN_DLL"


#--------------------------------------------------------------------------------
#     LCCD
#--------------------------------------------------------------------------------
export LCCD="/home/spanns/ilcsoft/v01-16-02/lccd/v01-02"


#--------------------------------------------------------------------------------
#     LCIO
#--------------------------------------------------------------------------------
export LCIO="/home/spanns/ilcsoft/v01-16-02/lcio/v02-03-03"
export PATH="$LCIO/tools:$LCIO/bin:$PATH"
export LD_LIBRARY_PATH="$LCIO/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     GSL
#--------------------------------------------------------------------------------
export GSL_HOME="/home/spanns/ilcsoft/v01-16-02/gsl/usr"
export PATH="$GSL_HOME/bin:$PATH"
export LD_LIBRARY_PATH="$GSL_HOME/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     CED
#--------------------------------------------------------------------------------
export PATH="/home/spanns/ilcsoft/v01-16-02/CED/v01-07/bin:$PATH"


#--------------------------------------------------------------------------------
#     CMake
#--------------------------------------------------------------------------------
export PATH="/home/spanns/ilcsoft/v01-16-02/CMake/usr/bin:$PATH"


#--------------------------------------------------------------------------------
#     ILCUTIL
#--------------------------------------------------------------------------------
export ilcutil="/home/spanns/ilcsoft/v01-16-02/ilcutil/v01-00"
export LD_LIBRARY_PATH="$ilcutil/lib:$LD_LIBRARY_PATH"
# --- additional comands ------- 
