#include "EUTelUtilityPrintEventNumber.h"

// C++
#include <iostream>
#include <iomanip>

// Aida
#ifdef MARLIN_USE_AIDA
//AIDA
#include <AIDA/AIDA.h>
#include <marlin/AIDAProcessor.h>
#endif

// LCIO
#include "UTIL/LCTOOLS.h"

using namespace lcio;
using namespace marlin;
using namespace eutelescope;

EUTelUtilityPrintEventNumber aPrintEventNumber ;
    

EUTelUtilityPrintEventNumber::EUTelUtilityPrintEventNumber() : 
  Processor("EUTelUtilityPrintEventNumber") {
  /* the constructor call first the super constructor which the name 
   * of the processor
   * this must by the same as the class name.
   */
	
  /* description of the processor which will be displayed in the
   * steering file autometicly generated by 
   * marlin (use MarlinTPC -x (XML-format) or MarlinTPXC -l (text format))
   */
  _description = "EUTelUtilityPrintEventNumber prints event number to screen"
    " depending on the verbosity level" ;	
	
  /* register steering parameters: name, description, class-variable, default value
   * the type will by definded by the type of the default value
   * string, double, float and int are possible
   * plaese note to get a float you must cast in C++: (float) 1.3 
   */
  registerProcessorParameter( "EveryNEvents" , 
			      "Print event number every n Events (default 100)"  ,
			      _everyNEvents ,
			      100 ) ;
  registerOptionalParameter( "printTimestamp" , 
			      "print the event timestamp as read from LCIO"  ,
			      _printTimestamp ,
			     static_cast< bool >(0) ) ;	
}
    
    
void EUTelUtilityPrintEventNumber::init() { 
  // this method is called only once even when the rewind is active
  // usually a good idea to

  printParameters ();	
}
    
void EUTelUtilityPrintEventNumber::processRunHeader( LCRunHeader* run) { 
	
      
  run->parameters().setValue( _processorName + "_revision", "$Rev: 699 $");

  for ( ProcParamMap::iterator i = _map.begin(); i != _map.end(); i++ ) {
    if ( ! i->second->isOptional() || i->second->valueSet() ) {
      run->parameters().setValue( _processorName + "_" + i->second->name(), 
				  i->second->value() );
    }
  }

  totalruns++;
} 
    
void EUTelUtilityPrintEventNumber::processEvent( LCEvent * evt ) { 

      
  if ( evt->getEventNumber() <= 10 ||
       (evt->getEventNumber() <= 100 && evt->getEventNumber()%10 == 0) ||
       evt->getEventNumber()%_everyNEvents == 0) {
    streamlog_out(MESSAGE5) << "Processing event " 
			    << std::setw(7) << evt->getEventNumber() 
			    << " in run " << evt->getRunNumber();
    if(_printTimestamp) streamlog_out(MESSAGE5) << ", timestamp " << evt->getTimeStamp();
    streamlog_out(MESSAGE5) << std::endl;
  }
  else {
    streamlog_out(DEBUG5) << "Processing event " 
			    << std::setw(7) << evt->getEventNumber() 
			    << " in run " << evt->getRunNumber();
    if(_printTimestamp) streamlog_out(DEBUG5) << ", timestamp " << evt->getTimeStamp();
    streamlog_out(DEBUG5) << std::endl;
  }
  totalevents++;
}
    
    
void EUTelUtilityPrintEventNumber::check( LCEvent * /* evt */ ) { 
  /* Nothing to do here... */
}

    
    
void EUTelUtilityPrintEventNumber::end(){ 
  streamlog_out(MESSAGE4) << "Finished. Processed " << totalevents 
    			  << " events in " << totalruns << " runs in total."
			  << std::endl ;
}
